[package]
name = "omniglot-tock"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
omniglot.workspace = true
kernel.workspace = true
tock-tbf.workspace = true
rv32i.workspace = true